module.exports = ['United States',
    'China',
    'United Kingdom',
    'India',
    'Nigeria',
    'Egypt',
    'Iran',
    'Japan',
    'Korea',
    'Hong Kong',
    'Turkey',
    'Pakistan',
    'Bangladesh',
    'Indonesia',
    'Trinidad and Tobago',
    'Nepal'];
